export interface EmojiEntry {
  emoji: string;
  label: string;
  keywords?: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

const emoji = (value: string, label: string, keywords?: string): EmojiEntry => ({
  emoji: value,
  label,
  keywords,
});

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys & emotion',
    icon: '😀',
    emojis: [
      emoji('😀', 'Grinning face', 'happy smile'),
      emoji('😃', 'Grinning face with big eyes', 'happy smile'),
      emoji('😄', 'Grinning face with smiling eyes', 'happy laugh'),
      emoji('😁', 'Beaming face', 'happy grin'),
      emoji('😆', 'Grinning squinting face', 'laugh happy'),
      emoji('😅', 'Grinning face with sweat', 'nervous relief'),
      emoji('🤣', 'Rolling on the floor laughing', 'rofl lol'),
      emoji('😂', 'Face with tears of joy', 'laugh cry lol'),
      emoji('🙂', 'Slightly smiling face', 'smile'),
      emoji('🙃', 'Upside-down face', 'silly sarcasm'),
      emoji('🫠', 'Melting face', 'hot embarrassed'),
      emoji('😉', 'Winking face', 'wink playful'),
      emoji('😊', 'Smiling face with smiling eyes', 'happy blush'),
      emoji('😇', 'Smiling face with halo', 'angel innocent'),
      emoji('🥰', 'Smiling face with hearts', 'love adore'),
      emoji('😍', 'Heart eyes', 'love crush'),
      emoji('🤩', 'Star-struck', 'excited wow'),
      emoji('😘', 'Face blowing a kiss', 'love kiss'),
      emoji('😋', 'Face savoring food', 'yum delicious'),
      emoji('😛', 'Face with tongue', 'playful silly'),
      emoji('🤪', 'Zany face', 'crazy silly'),
      emoji('😎', 'Smiling face with sunglasses', 'cool'),
      emoji('🥳', 'Partying face', 'celebrate birthday'),
      emoji('🤗', 'Smiling face with open hands', 'hug support'),
      emoji('🤭', 'Face with hand over mouth', 'oops giggle'),
      emoji('🫢', 'Face with open eyes and hand over mouth', 'gasp surprise'),
      emoji('🫣', 'Face with peeking eye', 'peek nervous'),
      emoji('🤔', 'Thinking face', 'hmm consider'),
      emoji('🫡', 'Saluting face', 'respect yes'),
      emoji('🤨', 'Face with raised eyebrow', 'skeptical doubt'),
      emoji('😐', 'Neutral face', 'blank'),
      emoji('😑', 'Expressionless face', 'blank annoyed'),
      emoji('😶', 'Face without mouth', 'silent speechless'),
      emoji('🫥', 'Dotted line face', 'invisible disappear'),
      emoji('😏', 'Smirking face', 'smirk'),
      emoji('😒', 'Unamused face', 'annoyed bored'),
      emoji('🙄', 'Face with rolling eyes', 'eyeroll'),
      emoji('😬', 'Grimacing face', 'awkward nervous'),
      emoji('😌', 'Relieved face', 'calm peace'),
      emoji('😔', 'Pensive face', 'sad thoughtful'),
      emoji('😪', 'Sleepy face', 'tired'),
      emoji('🤤', 'Drooling face', 'hungry'),
      emoji('😴', 'Sleeping face', 'sleep tired'),
      emoji('😷', 'Face with medical mask', 'sick health'),
      emoji('🤒', 'Face with thermometer', 'sick fever'),
      emoji('🤕', 'Face with head bandage', 'hurt injured'),
      emoji('🤢', 'Nauseated face', 'sick gross'),
      emoji('🥵', 'Hot face', 'heat sweating'),
      emoji('🥶', 'Cold face', 'freezing'),
      emoji('😵', 'Face with crossed-out eyes', 'dizzy'),
      emoji('🤯', 'Exploding head', 'mind blown shocked'),
      emoji('🥹', 'Face holding back tears', 'touched grateful'),
      emoji('😟', 'Worried face', 'concern'),
      emoji('🙁', 'Slightly frowning face', 'sad'),
      emoji('☹️', 'Frowning face', 'sad'),
      emoji('😮', 'Face with open mouth', 'surprised wow'),
      emoji('😲', 'Astonished face', 'shocked surprise'),
      emoji('😳', 'Flushed face', 'embarrassed surprised'),
      emoji('🥺', 'Pleading face', 'please puppy eyes'),
      emoji('😢', 'Crying face', 'sad tear'),
      emoji('😭', 'Loudly crying face', 'sad sob'),
      emoji('😱', 'Face screaming in fear', 'scared horror'),
      emoji('😖', 'Confounded face', 'frustrated'),
      emoji('😣', 'Persevering face', 'struggle'),
      emoji('😞', 'Disappointed face', 'sad'),
      emoji('😤', 'Face with steam from nose', 'angry triumph'),
      emoji('😡', 'Enraged face', 'angry mad'),
      emoji('🤬', 'Face with symbols on mouth', 'swearing angry'),
      emoji('😈', 'Smiling face with horns', 'devil mischievous'),
      emoji('💀', 'Skull', 'dead dying lol'),
      emoji('💩', 'Pile of poo', 'poop funny'),
      emoji('🤡', 'Clown face', 'clown silly'),
      emoji('👻', 'Ghost', 'halloween spooky'),
      emoji('👽', 'Alien', 'ufo space'),
      emoji('🤖', 'Robot', 'bot ai'),
      emoji('😺', 'Grinning cat', 'cat happy'),
      emoji('😹', 'Cat with tears of joy', 'cat laugh'),
      emoji('😻', 'Smiling cat with heart eyes', 'cat love'),
      emoji('🙈', 'See-no-evil monkey', 'monkey embarrassed'),
      emoji('🙉', 'Hear-no-evil monkey', 'monkey'),
      emoji('🙊', 'Speak-no-evil monkey', 'monkey secret'),
      emoji('💋', 'Kiss mark', 'lips love'),
      emoji('💯', 'Hundred points', 'perfect score'),
      emoji('💢', 'Anger symbol', 'mad'),
      emoji('💥', 'Collision', 'boom explosion'),
      emoji('💫', 'Dizzy', 'star'),
      emoji('💦', 'Sweat droplets', 'water'),
      emoji('💨', 'Dashing away', 'fast wind'),
      emoji('🕳️', 'Hole', 'empty'),
      emoji('💬', 'Speech balloon', 'comment chat'),
      emoji('💭', 'Thought balloon', 'think'),
      emoji('❤️', 'Red heart', 'love'),
      emoji('🩷', 'Pink heart', 'love'),
      emoji('🧡', 'Orange heart', 'love'),
      emoji('💛', 'Yellow heart', 'love'),
      emoji('💚', 'Green heart', 'love'),
      emoji('💙', 'Blue heart', 'love'),
      emoji('💜', 'Purple heart', 'love'),
      emoji('🖤', 'Black heart', 'love'),
      emoji('🤍', 'White heart', 'love'),
      emoji('🤎', 'Brown heart', 'love'),
      emoji('💔', 'Broken heart', 'heartbreak sad'),
      emoji('💕', 'Two hearts', 'love'),
      emoji('💖', 'Sparkling heart', 'love'),
      emoji('💘', 'Heart with arrow', 'love cupid'),
    ],
  },
  {
    id: 'people',
    label: 'People & body',
    icon: '👋',
    emojis: [
      emoji('👋', 'Waving hand', 'hello goodbye'),
      emoji('🤚', 'Raised back of hand', 'stop'),
      emoji('🖐️', 'Hand with fingers splayed', 'five stop'),
      emoji('✋', 'Raised hand', 'stop high five'),
      emoji('🖖', 'Vulcan salute', 'spock prosper'),
      emoji('🫱', 'Rightwards hand', 'handshake'),
      emoji('🫲', 'Leftwards hand', 'handshake'),
      emoji('👌', 'OK hand', 'okay perfect'),
      emoji('🤌', 'Pinched fingers', 'italian gesture'),
      emoji('🤏', 'Pinching hand', 'small little'),
      emoji('✌️', 'Victory hand', 'peace two'),
      emoji('🤞', 'Crossed fingers', 'luck hope'),
      emoji('🫰', 'Hand with index finger and thumb crossed', 'finger heart money'),
      emoji('🤟', 'Love-you gesture', 'ily hand'),
      emoji('🤘', 'Sign of the horns', 'rock metal'),
      emoji('🤙', 'Call me hand', 'phone shaka'),
      emoji('👈', 'Backhand index pointing left', 'left'),
      emoji('👉', 'Backhand index pointing right', 'right'),
      emoji('👆', 'Backhand index pointing up', 'up'),
      emoji('👇', 'Backhand index pointing down', 'down'),
      emoji('☝️', 'Index pointing up', 'one'),
      emoji('🫵', 'Index pointing at the viewer', 'you'),
      emoji('👍', 'Thumbs up', 'yes like approve'),
      emoji('👎', 'Thumbs down', 'no dislike'),
      emoji('✊', 'Raised fist', 'power solidarity'),
      emoji('👊', 'Oncoming fist', 'fist bump'),
      emoji('🤛', 'Left-facing fist', 'fist bump'),
      emoji('🤜', 'Right-facing fist', 'fist bump'),
      emoji('👏', 'Clapping hands', 'applause congrats'),
      emoji('🙌', 'Raising hands', 'celebrate praise'),
      emoji('🫶', 'Heart hands', 'love support'),
      emoji('👐', 'Open hands', 'hug'),
      emoji('🤲', 'Palms up together', 'receive prayer'),
      emoji('🤝', 'Handshake', 'deal agreement'),
      emoji('🙏', 'Folded hands', 'please thanks pray'),
      emoji('✍️', 'Writing hand', 'write author'),
      emoji('💅', 'Nail polish', 'nails sass'),
      emoji('🤳', 'Selfie', 'camera phone'),
      emoji('💪', 'Flexed biceps', 'strong muscle'),
      emoji('🦾', 'Mechanical arm', 'robot strength'),
      emoji('🧠', 'Brain', 'smart think'),
      emoji('👀', 'Eyes', 'look watching'),
      emoji('👁️', 'Eye', 'look see'),
      emoji('👂', 'Ear', 'listen hear'),
      emoji('🦻', 'Ear with hearing aid', 'accessibility listen'),
      emoji('👃', 'Nose', 'smell'),
      emoji('🫂', 'People hugging', 'hug support'),
      emoji('👶', 'Baby', 'child'),
      emoji('🧑', 'Person', 'adult'),
      emoji('👩', 'Woman', 'person'),
      emoji('👨', 'Man', 'person'),
      emoji('🧑‍💻', 'Technologist', 'developer coder computer'),
      emoji('🧑‍🎨', 'Artist', 'creative paint'),
      emoji('🧑‍🚀', 'Astronaut', 'space'),
      emoji('🦸', 'Superhero', 'hero power'),
      emoji('🧙', 'Mage', 'wizard magic'),
      emoji('🧚', 'Fairy', 'magic'),
      emoji('🧛', 'Vampire', 'halloween'),
      emoji('🧟', 'Zombie', 'halloween undead'),
      emoji('🕺', 'Man dancing', 'dance party'),
      emoji('💃', 'Woman dancing', 'dance party'),
      emoji('🏃', 'Person running', 'run exercise'),
      emoji('🚶', 'Person walking', 'walk'),
      emoji('🧘', 'Person in lotus position', 'meditate calm'),
    ],
  },
  {
    id: 'animals',
    label: 'Animals & nature',
    icon: '🐻',
    emojis: [
      emoji('🐶', 'Dog face', 'pet puppy'),
      emoji('🐱', 'Cat face', 'pet kitten'),
      emoji('🐭', 'Mouse face', 'animal'),
      emoji('🐹', 'Hamster', 'pet'),
      emoji('🐰', 'Rabbit face', 'bunny'),
      emoji('🦊', 'Fox', 'animal'),
      emoji('🐻', 'Bear', 'animal'),
      emoji('🐼', 'Panda', 'animal'),
      emoji('🐨', 'Koala', 'animal'),
      emoji('🐯', 'Tiger face', 'animal'),
      emoji('🦁', 'Lion', 'animal'),
      emoji('🐮', 'Cow face', 'animal'),
      emoji('🐷', 'Pig face', 'animal'),
      emoji('🐸', 'Frog', 'animal'),
      emoji('🐵', 'Monkey face', 'animal'),
      emoji('🐔', 'Chicken', 'bird'),
      emoji('🐧', 'Penguin', 'bird'),
      emoji('🐦', 'Bird', 'animal'),
      emoji('🐤', 'Baby chick', 'bird'),
      emoji('🦆', 'Duck', 'bird'),
      emoji('🦅', 'Eagle', 'bird'),
      emoji('🦉', 'Owl', 'bird night'),
      emoji('🦇', 'Bat', 'animal night'),
      emoji('🐺', 'Wolf', 'animal'),
      emoji('🐗', 'Boar', 'animal'),
      emoji('🐴', 'Horse face', 'animal'),
      emoji('🦄', 'Unicorn', 'magic'),
      emoji('🐝', 'Honeybee', 'bee insect'),
      emoji('🪲', 'Beetle', 'insect bug'),
      emoji('🦋', 'Butterfly', 'insect'),
      emoji('🐌', 'Snail', 'slow'),
      emoji('🐞', 'Lady beetle', 'bug insect'),
      emoji('🐜', 'Ant', 'insect'),
      emoji('🪰', 'Fly', 'insect'),
      emoji('🕷️', 'Spider', 'bug'),
      emoji('🦂', 'Scorpion', 'animal'),
      emoji('🐢', 'Turtle', 'slow'),
      emoji('🐍', 'Snake', 'animal'),
      emoji('🦎', 'Lizard', 'animal'),
      emoji('🐙', 'Octopus', 'ocean'),
      emoji('🦑', 'Squid', 'ocean'),
      emoji('🦀', 'Crab', 'ocean'),
      emoji('🐠', 'Tropical fish', 'ocean'),
      emoji('🐟', 'Fish', 'ocean'),
      emoji('🐬', 'Dolphin', 'ocean'),
      emoji('🐳', 'Spouting whale', 'ocean'),
      emoji('🦈', 'Shark', 'ocean'),
      emoji('🐊', 'Crocodile', 'animal'),
      emoji('🐘', 'Elephant', 'animal'),
      emoji('🦒', 'Giraffe', 'animal'),
      emoji('🦘', 'Kangaroo', 'animal'),
      emoji('🐕', 'Dog', 'pet'),
      emoji('🐈', 'Cat', 'pet'),
      emoji('🐾', 'Paw prints', 'pet animal'),
      emoji('🌵', 'Cactus', 'plant desert'),
      emoji('🎄', 'Christmas tree', 'holiday'),
      emoji('🌲', 'Evergreen tree', 'nature'),
      emoji('🌳', 'Deciduous tree', 'nature'),
      emoji('🌴', 'Palm tree', 'tropical'),
      emoji('🪴', 'Potted plant', 'house plant'),
      emoji('🌱', 'Seedling', 'grow plant'),
      emoji('🌿', 'Herb', 'plant leaf'),
      emoji('☘️', 'Shamrock', 'luck plant'),
      emoji('🍀', 'Four leaf clover', 'luck'),
      emoji('🍁', 'Maple leaf', 'fall autumn canada'),
      emoji('🍂', 'Fallen leaf', 'fall autumn'),
      emoji('🍄', 'Mushroom', 'fungus'),
      emoji('🌷', 'Tulip', 'flower'),
      emoji('🌹', 'Rose', 'flower love'),
      emoji('🌻', 'Sunflower', 'flower'),
      emoji('🌼', 'Blossom', 'flower'),
      emoji('🪻', 'Hyacinth', 'flower'),
      emoji('🌸', 'Cherry blossom', 'flower spring'),
      emoji('💐', 'Bouquet', 'flowers gift'),
      emoji('🌈', 'Rainbow', 'weather pride'),
      emoji('☀️', 'Sun', 'weather sunny'),
      emoji('🌤️', 'Sun behind small cloud', 'weather'),
      emoji('☁️', 'Cloud', 'weather'),
      emoji('🌧️', 'Cloud with rain', 'weather'),
      emoji('⛈️', 'Cloud with lightning and rain', 'storm weather'),
      emoji('❄️', 'Snowflake', 'cold winter'),
      emoji('🔥', 'Fire', 'hot trending lit'),
      emoji('🌊', 'Water wave', 'ocean sea'),
      emoji('✨', 'Sparkles', 'shine magic'),
      emoji('⭐', 'Star', 'favorite'),
      emoji('🌟', 'Glowing star', 'shine'),
      emoji('🌙', 'Crescent moon', 'night'),
      emoji('🌍', 'Globe showing Europe and Africa', 'earth world'),
    ],
  },
  {
    id: 'food',
    label: 'Food & drink',
    icon: '🍕',
    emojis: [
      emoji('🍏', 'Green apple', 'fruit'),
      emoji('🍎', 'Red apple', 'fruit'),
      emoji('🍐', 'Pear', 'fruit'),
      emoji('🍊', 'Tangerine', 'orange fruit'),
      emoji('🍋', 'Lemon', 'fruit'),
      emoji('🍌', 'Banana', 'fruit'),
      emoji('🍉', 'Watermelon', 'fruit'),
      emoji('🍇', 'Grapes', 'fruit'),
      emoji('🍓', 'Strawberry', 'fruit'),
      emoji('🫐', 'Blueberries', 'fruit'),
      emoji('🍒', 'Cherries', 'fruit'),
      emoji('🍑', 'Peach', 'fruit'),
      emoji('🥭', 'Mango', 'fruit'),
      emoji('🍍', 'Pineapple', 'fruit'),
      emoji('🥥', 'Coconut', 'fruit'),
      emoji('🥝', 'Kiwi fruit', 'fruit'),
      emoji('🍅', 'Tomato', 'vegetable'),
      emoji('🥑', 'Avocado', 'food'),
      emoji('🥦', 'Broccoli', 'vegetable'),
      emoji('🥕', 'Carrot', 'vegetable'),
      emoji('🌽', 'Ear of corn', 'vegetable'),
      emoji('🌶️', 'Hot pepper', 'spicy'),
      emoji('🍞', 'Bread', 'food'),
      emoji('🥐', 'Croissant', 'bread breakfast'),
      emoji('🥨', 'Pretzel', 'food'),
      emoji('🧀', 'Cheese wedge', 'food'),
      emoji('🥚', 'Egg', 'breakfast'),
      emoji('🍳', 'Cooking', 'egg breakfast'),
      emoji('🥞', 'Pancakes', 'breakfast'),
      emoji('🥓', 'Bacon', 'breakfast'),
      emoji('🍔', 'Hamburger', 'burger fast food'),
      emoji('🍟', 'French fries', 'fast food'),
      emoji('🍕', 'Pizza', 'food'),
      emoji('🌭', 'Hot dog', 'food'),
      emoji('🥪', 'Sandwich', 'food'),
      emoji('🌮', 'Taco', 'mexican food'),
      emoji('🌯', 'Burrito', 'mexican food'),
      emoji('🥗', 'Green salad', 'healthy food'),
      emoji('🍝', 'Spaghetti', 'pasta food'),
      emoji('🍜', 'Steaming bowl', 'noodles soup'),
      emoji('🍛', 'Curry rice', 'food'),
      emoji('🍣', 'Sushi', 'japanese food'),
      emoji('🍱', 'Bento box', 'japanese food'),
      emoji('🥟', 'Dumpling', 'food'),
      emoji('🍤', 'Fried shrimp', 'seafood'),
      emoji('🍚', 'Cooked rice', 'food'),
      emoji('🍦', 'Soft ice cream', 'dessert'),
      emoji('🍩', 'Doughnut', 'donut dessert'),
      emoji('🍪', 'Cookie', 'dessert'),
      emoji('🎂', 'Birthday cake', 'dessert celebration'),
      emoji('🍰', 'Shortcake', 'dessert'),
      emoji('🧁', 'Cupcake', 'dessert'),
      emoji('🍫', 'Chocolate bar', 'dessert'),
      emoji('🍿', 'Popcorn', 'movie snack'),
      emoji('🍯', 'Honey pot', 'sweet'),
      emoji('🍼', 'Baby bottle', 'drink'),
      emoji('☕', 'Hot beverage', 'coffee tea'),
      emoji('🫖', 'Teapot', 'tea'),
      emoji('🍵', 'Teacup without handle', 'tea'),
      emoji('🧃', 'Beverage box', 'juice'),
      emoji('🥤', 'Cup with straw', 'soda drink'),
      emoji('🧋', 'Bubble tea', 'boba drink'),
      emoji('🍺', 'Beer mug', 'drink'),
      emoji('🍻', 'Clinking beer mugs', 'cheers drink'),
      emoji('🥂', 'Clinking glasses', 'cheers celebration'),
      emoji('🍷', 'Wine glass', 'drink'),
      emoji('🍸', 'Cocktail glass', 'drink'),
      emoji('🍹', 'Tropical drink', 'cocktail'),
      emoji('🧊', 'Ice', 'cold'),
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      emoji('⚽', 'Soccer ball', 'football sport'),
      emoji('🏀', 'Basketball', 'sport'),
      emoji('🏈', 'American football', 'sport'),
      emoji('⚾', 'Baseball', 'sport'),
      emoji('🥎', 'Softball', 'sport'),
      emoji('🎾', 'Tennis', 'sport'),
      emoji('🏐', 'Volleyball', 'sport'),
      emoji('🏉', 'Rugby football', 'sport'),
      emoji('🥏', 'Flying disc', 'frisbee sport'),
      emoji('🎱', 'Pool 8 ball', 'billiards game'),
      emoji('🏓', 'Ping pong', 'table tennis'),
      emoji('🏸', 'Badminton', 'sport'),
      emoji('🏒', 'Ice hockey', 'sport'),
      emoji('🏏', 'Cricket game', 'sport'),
      emoji('🥅', 'Goal net', 'sport'),
      emoji('⛳', 'Flag in hole', 'golf'),
      emoji('🏹', 'Bow and arrow', 'archery'),
      emoji('🎣', 'Fishing pole', 'fish'),
      emoji('🤿', 'Diving mask', 'swim ocean'),
      emoji('🥊', 'Boxing glove', 'sport fight'),
      emoji('🛹', 'Skateboard', 'sport'),
      emoji('🛼', 'Roller skate', 'sport'),
      emoji('⛷️', 'Skier', 'snow sport'),
      emoji('🏂', 'Snowboarder', 'snow sport'),
      emoji('🏋️', 'Person lifting weights', 'gym exercise'),
      emoji('🤸', 'Person cartwheeling', 'gymnastics'),
      emoji('🏆', 'Trophy', 'winner award'),
      emoji('🥇', 'Gold medal', 'first winner'),
      emoji('🥈', 'Silver medal', 'second'),
      emoji('🥉', 'Bronze medal', 'third'),
      emoji('🎖️', 'Military medal', 'award'),
      emoji('🎗️', 'Reminder ribbon', 'awareness'),
      emoji('🎟️', 'Admission tickets', 'event'),
      emoji('🎪', 'Circus tent', 'event'),
      emoji('🎭', 'Performing arts', 'theater drama'),
      emoji('🎨', 'Artist palette', 'art paint'),
      emoji('🎬', 'Clapper board', 'film movie'),
      emoji('🎤', 'Microphone', 'sing music'),
      emoji('🎧', 'Headphone', 'music audio'),
      emoji('🎼', 'Musical score', 'music'),
      emoji('🎹', 'Musical keyboard', 'piano music'),
      emoji('🥁', 'Drum', 'music'),
      emoji('🎷', 'Saxophone', 'music'),
      emoji('🎺', 'Trumpet', 'music'),
      emoji('🎸', 'Guitar', 'music'),
      emoji('🎻', 'Violin', 'music'),
      emoji('🎲', 'Game die', 'dice game'),
      emoji('♟️', 'Chess pawn', 'game'),
      emoji('🎯', 'Bullseye', 'target goal'),
      emoji('🎳', 'Bowling', 'game'),
      emoji('🎮', 'Video game', 'gaming controller'),
      emoji('🕹️', 'Joystick', 'gaming'),
      emoji('🧩', 'Puzzle piece', 'game'),
      emoji('🎉', 'Party popper', 'celebration congrats'),
      emoji('🎊', 'Confetti ball', 'celebration'),
      emoji('🎈', 'Balloon', 'party birthday'),
      emoji('🎁', 'Wrapped gift', 'present birthday'),
    ],
  },
  {
    id: 'travel',
    label: 'Travel & places',
    icon: '✈️',
    emojis: [
      emoji('🚗', 'Automobile', 'car travel'),
      emoji('🚕', 'Taxi', 'car travel'),
      emoji('🚌', 'Bus', 'travel'),
      emoji('🏎️', 'Racing car', 'fast'),
      emoji('🚓', 'Police car', 'emergency'),
      emoji('🚑', 'Ambulance', 'emergency'),
      emoji('🚒', 'Fire engine', 'emergency'),
      emoji('🚚', 'Delivery truck', 'shipping'),
      emoji('🚲', 'Bicycle', 'bike travel'),
      emoji('🏍️', 'Motorcycle', 'travel'),
      emoji('🚂', 'Locomotive', 'train travel'),
      emoji('🚆', 'Train', 'travel'),
      emoji('🚇', 'Metro', 'subway travel'),
      emoji('🚀', 'Rocket', 'space launch'),
      emoji('🛸', 'Flying saucer', 'ufo space'),
      emoji('✈️', 'Airplane', 'flight travel'),
      emoji('🛫', 'Airplane departure', 'flight travel'),
      emoji('🛬', 'Airplane arrival', 'flight travel'),
      emoji('⛵', 'Sailboat', 'sea travel'),
      emoji('🚢', 'Ship', 'sea travel'),
      emoji('⚓', 'Anchor', 'ship sea'),
      emoji('⛽', 'Fuel pump', 'gas petrol'),
      emoji('🚧', 'Construction', 'barrier work'),
      emoji('🚦', 'Vertical traffic light', 'road'),
      emoji('🗺️', 'World map', 'travel'),
      emoji('🗿', 'Moai', 'statue'),
      emoji('🗽', 'Statue of Liberty', 'new york usa'),
      emoji('🗼', 'Tokyo tower', 'japan'),
      emoji('🏰', 'Castle', 'travel'),
      emoji('🏯', 'Japanese castle', 'travel'),
      emoji('🏟️', 'Stadium', 'sport venue'),
      emoji('🎡', 'Ferris wheel', 'amusement park'),
      emoji('🎢', 'Roller coaster', 'amusement park'),
      emoji('⛲', 'Fountain', 'place'),
      emoji('⛺', 'Tent', 'camping'),
      emoji('🏠', 'House', 'home'),
      emoji('🏢', 'Office building', 'work'),
      emoji('🏥', 'Hospital', 'health'),
      emoji('🏫', 'School', 'education'),
      emoji('🏪', 'Convenience store', 'shop'),
      emoji('🏙️', 'Cityscape', 'city'),
      emoji('🌄', 'Sunrise over mountains', 'morning nature'),
      emoji('🌅', 'Sunrise', 'morning'),
      emoji('🌆', 'Cityscape at dusk', 'evening'),
      emoji('🌇', 'Sunset', 'evening'),
      emoji('🌌', 'Milky Way', 'space night'),
      emoji('🎆', 'Fireworks', 'celebration'),
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      emoji('⌚', 'Watch', 'time'),
      emoji('📱', 'Mobile phone', 'smartphone'),
      emoji('💻', 'Laptop', 'computer work'),
      emoji('⌨️', 'Keyboard', 'computer type'),
      emoji('🖥️', 'Desktop computer', 'monitor'),
      emoji('🖨️', 'Printer', 'office'),
      emoji('🖱️', 'Computer mouse', 'computer'),
      emoji('💾', 'Floppy disk', 'save storage'),
      emoji('💿', 'Optical disk', 'cd'),
      emoji('📷', 'Camera', 'photo'),
      emoji('📸', 'Camera with flash', 'photo'),
      emoji('📹', 'Video camera', 'film'),
      emoji('🎥', 'Movie camera', 'film'),
      emoji('📺', 'Television', 'tv'),
      emoji('📻', 'Radio', 'audio'),
      emoji('🎙️', 'Studio microphone', 'podcast audio'),
      emoji('⏰', 'Alarm clock', 'time'),
      emoji('⌛', 'Hourglass done', 'time wait'),
      emoji('🔋', 'Battery', 'power'),
      emoji('🔌', 'Electric plug', 'power'),
      emoji('💡', 'Light bulb', 'idea'),
      emoji('🔦', 'Flashlight', 'light'),
      emoji('🕯️', 'Candle', 'light'),
      emoji('🧯', 'Fire extinguisher', 'safety'),
      emoji('💸', 'Money with wings', 'cash spend'),
      emoji('💵', 'Dollar banknote', 'money cash'),
      emoji('💰', 'Money bag', 'cash rich'),
      emoji('💳', 'Credit card', 'payment'),
      emoji('🧾', 'Receipt', 'payment bill'),
      emoji('💎', 'Gem stone', 'diamond jewel'),
      emoji('⚖️', 'Balance scale', 'law justice'),
      emoji('🔧', 'Wrench', 'tool fix'),
      emoji('🔨', 'Hammer', 'tool build'),
      emoji('🛠️', 'Hammer and wrench', 'tools build'),
      emoji('🧰', 'Toolbox', 'tools'),
      emoji('🧲', 'Magnet', 'attract'),
      emoji('🔬', 'Microscope', 'science'),
      emoji('🔭', 'Telescope', 'space science'),
      emoji('🛰️', 'Satellite', 'space'),
      emoji('💊', 'Pill', 'medicine health'),
      emoji('🩹', 'Adhesive bandage', 'health'),
      emoji('🔑', 'Key', 'lock'),
      emoji('🔒', 'Locked', 'security'),
      emoji('🔓', 'Unlocked', 'security'),
      emoji('🔔', 'Bell', 'notification'),
      emoji('🎵', 'Musical note', 'music'),
      emoji('📢', 'Loudspeaker', 'announcement'),
      emoji('📣', 'Megaphone', 'announcement'),
      emoji('✏️', 'Pencil', 'write edit'),
      emoji('🖊️', 'Pen', 'write'),
      emoji('📝', 'Memo', 'write note'),
      emoji('📁', 'File folder', 'document'),
      emoji('📌', 'Pushpin', 'pin'),
      emoji('📍', 'Round pushpin', 'location'),
      emoji('📎', 'Paperclip', 'attachment'),
      emoji('📚', 'Books', 'read study'),
      emoji('📖', 'Open book', 'read'),
      emoji('🔗', 'Link', 'url chain'),
      emoji('✂️', 'Scissors', 'cut'),
      emoji('🗑️', 'Wastebasket', 'trash delete'),
      emoji('📦', 'Package', 'box shipping'),
      emoji('🛒', 'Shopping cart', 'shop'),
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '💙',
    emojis: [
      emoji('✅', 'Check mark button', 'yes done complete'),
      emoji('❌', 'Cross mark', 'no wrong'),
      emoji('❓', 'Red question mark', 'question'),
      emoji('❗', 'Red exclamation mark', 'important alert'),
      emoji('‼️', 'Double exclamation mark', 'important'),
      emoji('⁉️', 'Exclamation question mark', 'surprise'),
      emoji('⭕', 'Hollow red circle', 'circle correct'),
      emoji('🚫', 'Prohibited', 'no banned stop'),
      emoji('⚠️', 'Warning', 'alert caution'),
      emoji('♻️', 'Recycling symbol', 'recycle green'),
      emoji('🔱', 'Trident emblem', 'symbol'),
      emoji('⚜️', 'Fleur-de-lis', 'symbol'),
      emoji('🔰', 'Japanese symbol for beginner', 'new'),
      emoji('📛', 'Name badge', 'symbol'),
      emoji('🌀', 'Cyclone', 'swirl'),
      emoji('💤', 'Zzz', 'sleep'),
      emoji('🚻', 'Restroom', 'toilet'),
      emoji('♿', 'Wheelchair symbol', 'accessibility'),
      emoji('🛜', 'Wireless', 'wifi internet'),
      emoji('🔞', 'No one under eighteen', 'adult'),
      emoji('⬆️', 'Up arrow', 'north'),
      emoji('↗️', 'Up-right arrow', 'northeast'),
      emoji('➡️', 'Right arrow', 'east next'),
      emoji('↘️', 'Down-right arrow', 'southeast'),
      emoji('⬇️', 'Down arrow', 'south'),
      emoji('↙️', 'Down-left arrow', 'southwest'),
      emoji('⬅️', 'Left arrow', 'west back'),
      emoji('↖️', 'Up-left arrow', 'northwest'),
      emoji('↔️', 'Left-right arrow', 'both'),
      emoji('↕️', 'Up-down arrow', 'both'),
      emoji('🔄', 'Counterclockwise arrows', 'refresh sync'),
      emoji('▶️', 'Play button', 'start video'),
      emoji('⏸️', 'Pause button', 'stop video'),
      emoji('⏹️', 'Stop button', 'video'),
      emoji('⏩', 'Fast-forward button', 'video'),
      emoji('🔀', 'Shuffle tracks button', 'music'),
      emoji('➕', 'Plus', 'add'),
      emoji('➖', 'Minus', 'remove'),
      emoji('✖️', 'Multiply', 'times close'),
      emoji('➗', 'Divide', 'math'),
      emoji('🟰', 'Heavy equals sign', 'math'),
      emoji('♾️', 'Infinity', 'forever'),
      emoji('™️', 'Trade mark', 'trademark'),
      emoji('©️', 'Copyright', 'symbol'),
      emoji('®️', 'Registered', 'symbol'),
      emoji('#️⃣', 'Keycap number sign', 'hashtag'),
      emoji('*️⃣', 'Keycap asterisk', 'star'),
      emoji('0️⃣', 'Keycap zero', 'number'),
      emoji('1️⃣', 'Keycap one', 'number'),
      emoji('2️⃣', 'Keycap two', 'number'),
      emoji('3️⃣', 'Keycap three', 'number'),
      emoji('🔵', 'Blue circle', 'shape'),
      emoji('🟢', 'Green circle', 'shape'),
      emoji('🟡', 'Yellow circle', 'shape'),
      emoji('🟠', 'Orange circle', 'shape'),
      emoji('🔴', 'Red circle', 'shape'),
      emoji('🟣', 'Purple circle', 'shape'),
      emoji('⚫', 'Black circle', 'shape'),
      emoji('⚪', 'White circle', 'shape'),
      emoji('🔶', 'Large orange diamond', 'shape'),
      emoji('🔷', 'Large blue diamond', 'shape'),
      emoji('▪️', 'Black small square', 'shape'),
      emoji('▫️', 'White small square', 'shape'),
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    icon: '🏳️',
    emojis: [
      emoji('🏁', 'Chequered flag', 'finish racing'),
      emoji('🚩', 'Triangular flag', 'warning red'),
      emoji('🎌', 'Crossed flags', 'celebration japan'),
      emoji('🏳️', 'White flag', 'peace surrender'),
      emoji('🏴', 'Black flag', 'flag'),
      emoji('🏳️‍🌈', 'Rainbow flag', 'pride lgbtq'),
      emoji('🏳️‍⚧️', 'Transgender flag', 'pride trans'),
      emoji('🇳🇵', 'Flag of Nepal', 'nepal'),
      emoji('🇺🇸', 'Flag of United States', 'usa america'),
      emoji('🇬🇧', 'Flag of United Kingdom', 'uk britain'),
      emoji('🇨🇦', 'Flag of Canada', 'canada'),
      emoji('🇲🇽', 'Flag of Mexico', 'mexico'),
      emoji('🇧🇷', 'Flag of Brazil', 'brazil'),
      emoji('🇦🇷', 'Flag of Argentina', 'argentina'),
      emoji('🇫🇷', 'Flag of France', 'france'),
      emoji('🇩🇪', 'Flag of Germany', 'germany'),
      emoji('🇮🇹', 'Flag of Italy', 'italy'),
      emoji('🇪🇸', 'Flag of Spain', 'spain'),
      emoji('🇵🇹', 'Flag of Portugal', 'portugal'),
      emoji('🇳🇱', 'Flag of Netherlands', 'netherlands holland'),
      emoji('🇸🇪', 'Flag of Sweden', 'sweden'),
      emoji('🇳🇴', 'Flag of Norway', 'norway'),
      emoji('🇩🇰', 'Flag of Denmark', 'denmark'),
      emoji('🇫🇮', 'Flag of Finland', 'finland'),
      emoji('🇨🇭', 'Flag of Switzerland', 'switzerland'),
      emoji('🇺🇦', 'Flag of Ukraine', 'ukraine'),
      emoji('🇵🇱', 'Flag of Poland', 'poland'),
      emoji('🇬🇷', 'Flag of Greece', 'greece'),
      emoji('🇹🇷', 'Flag of Türkiye', 'turkey'),
      emoji('🇮🇳', 'Flag of India', 'india'),
      emoji('🇧🇩', 'Flag of Bangladesh', 'bangladesh'),
      emoji('🇵🇰', 'Flag of Pakistan', 'pakistan'),
      emoji('🇱🇰', 'Flag of Sri Lanka', 'sri lanka'),
      emoji('🇨🇳', 'Flag of China', 'china'),
      emoji('🇯🇵', 'Flag of Japan', 'japan'),
      emoji('🇰🇷', 'Flag of South Korea', 'korea'),
      emoji('🇹🇭', 'Flag of Thailand', 'thailand'),
      emoji('🇸🇬', 'Flag of Singapore', 'singapore'),
      emoji('🇮🇩', 'Flag of Indonesia', 'indonesia'),
      emoji('🇵🇭', 'Flag of Philippines', 'philippines'),
      emoji('🇦🇺', 'Flag of Australia', 'australia'),
      emoji('🇳🇿', 'Flag of New Zealand', 'new zealand'),
      emoji('🇿🇦', 'Flag of South Africa', 'south africa'),
      emoji('🇳🇬', 'Flag of Nigeria', 'nigeria'),
      emoji('🇰🇪', 'Flag of Kenya', 'kenya'),
      emoji('🇪🇬', 'Flag of Egypt', 'egypt'),
      emoji('🇦🇪', 'Flag of United Arab Emirates', 'uae emirates'),
      emoji('🇸🇦', 'Flag of Saudi Arabia', 'saudi arabia'),
      emoji('🇮🇱', 'Flag of Israel', 'israel'),
      emoji('🇺🇳', 'United Nations flag', 'un world'),
    ],
  },
];

export const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap((category) => category.emojis);

export const EMOJI_BY_VALUE = new Map(ALL_EMOJIS.map((entry) => [entry.emoji, entry]));

export function searchEmojis(query: string): EmojiEntry[] {
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];

  return ALL_EMOJIS.filter((entry) => {
    const haystack = `${entry.label} ${entry.keywords ?? ''}`.toLocaleLowerCase();
    return terms.every((term) => haystack.includes(term));
  });
}
